const fmt=n=>Math.round(n).toLocaleString('ko-KR')+'원';const pct=n=>Number(n||0).toFixed(2)+'%';let state=PRMPortfolio.initial();
function cls(n){return n>0?'pos':n<0?'neg':''}
function syncPrices(){for(const p of state.positions){const px=PRMMarket.price(p.name);if(px>0)p.price=px}PRMPortfolio.save(state)}
function banner(){return `<div class="source-ok"><b>${PRMMarket.mode==='closing'?'🟢 오후 8시 확정 종가':'🟡 기본 시세'}</b>${PRMMarket.lastUpdated?' · 기준일 '+PRMMarket.lastUpdated:''}</div>`}
function render(){const r=PRMRisk.calc(state),h=PRMRisk.health(state);
const rows=state.positions.map((p,i)=>{const pl=p.qty*(p.price-p.avg),ret=p.avg?(p.price-p.avg)/p.avg*100:0,w=r.value?p.price*p.qty/r.value*100:0;return `<tr><td>${p.name}</td><td>${p.type}</td><td>${p.qty}</td><td>${fmt(p.avg)}</td><td><input data-i="${i}" type="number" value="${p.price}"></td><td class="${cls(pl)}">${fmt(pl)}</td><td class="${cls(ret)}">${ret.toFixed(2)}%</td><td>${w.toFixed(1)}%</td><td>${fmt(p.loan)}</td></tr>`}).join('');
document.getElementById('app').innerHTML=`<header><div><h1>Richman Portfolio Risk Manager</h1><p class="muted">오후 8시 확정 종가 · 거래 · 히스토리 · 투자일기 · AI 리스크 코치</p></div><div><button id="refresh">종가 다시 읽기</button><button id="snap">스냅샷 저장</button><button id="export">백업</button></div></header>${banner()}
<section class="kpis"><article><b>평가금액</b><span>${fmt(r.value)}</span></article><article><b>평가손익</b><span class="${cls(r.pnl)}">${fmt(r.pnl)}</span></article><article><b>순자산</b><span>${fmt(r.net)}</span></article><article><b>예수금</b><span>${fmt(state.cash)}</span></article><article><b>신용융자</b><span>${fmt(r.loan)}</span></article><article><b>담보비율</b><span>${pct(r.collateral)}</span></article><article><b>건강도</b><span>${h.score}/100</span></article></section>
<section class="panel"><h2>포지션</h2><div class="tablewrap"><table><thead><tr><th>종목</th><th>구분</th><th>수량</th><th>평단</th><th>현재가</th><th>손익</th><th>수익률</th><th>비중</th><th>신용</th></tr></thead><tbody>${rows}</tbody></table></div></section>
<section class="twocol"><div class="panel"><h2>담보 임계가격</h2>${[170,160,150,140].map(x=>`<div class="threshold"><b>${x}%</b><span>${fmt(PRMRisk.hynixThreshold(state,x))}</span></div>`).join('')}</div>
<div class="panel"><h2>AI 리스크 코치</h2><p>${PRMAI.coach(state)}</p><pre>${PRMAI.prompt(state)}</pre></div></section>
<section class="twocol"><div class="panel"><h2>거래 입력</h2><div class="formgrid"><select id="kind"><option value="buy">매수</option><option value="sell">매도</option><option value="repay">신용상환</option><option value="deposit">입금</option><option value="withdraw">출금</option></select><select id="name">${Object.keys(PRM_CONFIG.tickers).map(x=>`<option>${x}</option>`).join('')}</select><select id="type"><option>현금</option><option>유통융자</option><option>자기융자</option><option>신용</option></select><input id="qty" type="number" placeholder="수량"><input id="price" type="number" placeholder="가격"><input id="amount" type="number" placeholder="금액/상환액"><button id="applyTrade">반영</button></div></div>
<div class="panel"><h2>투자일기</h2><textarea id="diary">${PRMDiary.generate(state)}</textarea><button id="downloadDiary">TXT 저장</button></div></section>
<section class="panel"><h2>히스토리</h2>${PRMStorage.get('snapshots',[]).slice(-10).reverse().map(s=>`<div>${new Date(s.at).toLocaleString('ko-KR')} · 순자산 ${fmt(PRMRisk.calc(s.state).net)}</div>`).join('')||'아직 저장된 스냅샷이 없습니다.'}</section>`;
document.querySelectorAll('tbody input').forEach(el=>el.oninput=e=>{state.positions[+e.target.dataset.i].price=+e.target.value||0;PRMPortfolio.save(state);render()});
document.getElementById('refresh').onclick=refresh;document.getElementById('snap').onclick=()=>{PRMStorage.snapshot(JSON.parse(JSON.stringify(state)));render()};
document.getElementById('export').onclick=()=>download('richman-backup.json',PRMStorage.exportAll());document.getElementById('downloadDiary').onclick=()=>download('investment-diary.txt',document.getElementById('diary').value);
document.getElementById('applyTrade').onclick=()=>{PRMPortfolio.trade(state,{kind:kind.value,name:name.value,type:type.value,qty:+qty.value||0,price:+price.value||0,amount:+amount.value||0});render()}}
function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
async function refresh(){try{await PRMMarket.refresh();syncPrices();render()}catch(e){for(const p of state.positions){if(!p.price||p.price<=0)p.price=PRMMarket.price(p.name)}PRMPortfolio.save(state);render();console.warn(e)}}
render();refresh();
