const fmt=n=>Math.round(Number(n||0)).toLocaleString('ko-KR')+'원';
const pct=n=>Number(n||0).toFixed(2)+'%';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let state=PRMPortfolio.initial();
let scenarioPrice=PRMRisk.hynixCurrent(state)||PRM_CONFIG.fallbackPrices['SK하이닉스'];
let repayScenario=0;
function cls(n){return n>0?'pos':n<0?'neg':''}
function syncPrices(){for(const p of state.positions){const px=PRMMarket.price(p.name);if(px>0)p.price=px}scenarioPrice=PRMRisk.hynixCurrent(state);PRMPortfolio.save(state)}
function groupValues(s){const o={};for(const p of s.positions)o[p.name]=(o[p.name]||0)+p.qty*p.price;return o}
function kindLabel(k){return({buy:'매수',sell:'매도',repay:'신용상환',deposit:'입금',withdraw:'출금'})[k]||k}
function banner(){const info={live:['source-live','🔵 장중 시세 자동 반영','1분마다 확인'],closing:['source-ok','🟢 장 마감 최종 시세','다음 거래일 장중 자동 전환'],stale:['source-warning','🟡 장중 시세 갱신 지연','마지막 수신값 사용'],fallback:['source-warning','🟡 기본 시세 사용','시세 연결을 확인해 주세요'],loading:['source-warning','시세 확인 중','잠시만 기다려 주세요']}[PRMMarket.mode]||['source-warning','시세 확인 중',''];return `<div class="${info[0]}"><b>${info[1]}</b> · 기준 ${esc(PRMMarket.updatedLabel())} · ${info[2]}</div>`}
function positionRows(r){return state.positions.map((p,i)=>{const mv=p.qty*p.price,pl=p.qty*(p.price-p.avg),ret=p.avg?(p.price-p.avg)/p.avg*100:0,w=r.value?mv/r.value*100:0,open=PRMMarket.open(p.name);return `<tr><td>${esc(p.name)}</td><td>${esc(p.type)}</td><td>${p.qty.toLocaleString()}</td><td>${fmt(p.avg)}</td><td>${open?fmt(open):'—'}</td><td><input class="priceinput" data-price-i="${i}" type="number" value="${p.price}"></td><td>${fmt(mv)}</td><td class="${cls(pl)}">${fmt(pl)}</td><td class="${cls(ret)}">${ret.toFixed(2)}%</td><td>${w.toFixed(1)}%</td><td>${fmt(p.loan)}</td></tr>`}).join('')}
function stressRows(){return PRMRisk.stressRows(state).reverse().map(x=>`<tr><td>${fmt(x.price)}</td><td>${fmt(x.value)}</td><td class="${cls(x.pnl)}">${fmt(x.pnl)}</td><td>${fmt(x.net)}</td><td>${pct(x.collateral)}</td><td><span class="badge ${x.zone.key}">${x.zone.emoji} ${x.zone.label}</span></td></tr>`).join('')}
function tradeRows(){const arr=PRMPortfolio.trades().slice(-15).reverse();if(!arr.length)return '<div class="muted">아직 거래 기록이 없습니다.</div>';return `<div class="tradeList">${arr.map(t=>`<div class="tradeItem"><span>${new Date(t.at).toLocaleString('ko-KR')}</span><span><b>${kindLabel(t.kind)}</b> ${esc(t.name||'')} ${t.qty?Number(t.qty).toLocaleString()+'주':''} ${t.price?('@ '+fmt(t.price)):''}</span><span>${t.amount?fmt(t.amount):''}</span></div>`).join('')}</div>`}
function snapshotRows(){const arr=PRMStorage.get('snapshots',[]).slice(-12).reverse();if(!arr.length)return '<div class="muted">스냅샷을 저장하면 계좌 변화가 여기에 쌓입니다.</div>';return arr.map((x,idx)=>{const rr=PRMRisk.calc(x.state);return `<div class="snapshotItem"><span>${new Date(x.at).toLocaleString('ko-KR')} · 순자산 <b>${fmt(rr.net)}</b> · 담보 ${pct(rr.collateral)}</span><button class="tiny" data-load-snap="${idx}">이 상태 불러오기</button></div>`}).join('')}
function composition(r){const g=groupValues(state);return Object.entries(g).sort((a,b)=>b[1]-a[1]).map(([n,v])=>{const w=r.value?v/r.value*100:0;return `<div class="threshold"><span>${esc(n)} <span class="muted">${w.toFixed(1)}%</span></span><span><b>${fmt(v)}</b></span></div>`}).join('')}
function render(){
  const r=PRMRisk.calc(state),health=PRMRisk.health(state),z=health.zone;
  const scenario=PRMRisk.calc(state,{hynixPrice:scenarioPrice}),scenarioHealth=PRMRisk.health(state,{hynixPrice:scenarioPrice});
  const repay=Math.min(Math.max(0,repayScenario),Math.min(state.cash,r.loan));const afterRepay=PRMRisk.calc(state,{repay});
  const maxUsed=PRMRisk.maxLossUsed(state),maxLeft=Math.max(0,PRM_CONFIG.baseline.maxLoss-maxUsed);const monthlyLeft=Math.max(0,PRM_CONFIG.baseline.monthlyLossLimit-(state.monthlyLoss||0));
  const targetRepay180=PRMRisk.repaymentForTarget(state,180),targetRepay170=PRMRisk.repaymentForTarget(state,170);
  document.getElementById('app').innerHTML=`
  <div class="topbar"><div class="brand"><h1>Richman Portfolio Risk Manager <span class="version">v${PRM_CONFIG.version}</span></h1><small>장중 시세 기반 개인 HTS · 리스크 우선</small></div><div class="actions"><button id="refresh" class="primary">시세 다시 읽기</button><button id="snap">스냅샷</button><button id="backup">백업</button><button id="restoreBtn">복원</button><input id="restoreFile" type="file" accept="application/json" hidden><button id="reset" class="dangerbtn">기준계좌 초기화</button></div></div>
  <div class="nav"><a href="#dashboard">대시보드</a><a href="#portfolio">포트폴리오</a><a href="#risk">리스크센터</a><a href="#stress">하이닉스 스트레스</a><a href="#trade">거래</a><a href="#diary">투자일기</a><a href="#history">타임머신</a></div>${banner()}
  <section id="dashboard"><div class="kpis">
   <div class="kpi"><b>총 평가금액</b><strong>${fmt(r.value)}</strong><small>보유주식 시가</small></div>
   <div class="kpi"><b>평가손익</b><strong class="${cls(r.pnl)}">${fmt(r.pnl)}</strong><small>${pct(r.cost?r.pnl/r.cost*100:0)}</small></div>
   <div class="kpi"><b>순자산 추정</b><strong>${fmt(r.net)}</strong><small>평가+현금-융자</small></div>
   <div class="kpi"><b>예수금</b><strong>${fmt(state.cash)}</strong><small>거래 입력 반영</small></div>
   <div class="kpi"><b>신용융자</b><strong>${fmt(r.loan)}</strong><small>${pct(r.value?r.loan/r.value*100:0)} / 평가금액</small></div>
   <div class="kpi"><b>담보비율 추정</b><strong>${pct(r.collateral)}</strong><small>${z.emoji} ${z.label}</small></div>
   <div class="kpi"><b>계좌 건강도</b><strong>${health.score}/100</strong><small>집중도·레버리지 포함</small></div>
   <div class="kpi"><b>최대손실 여유</b><strong>${fmt(maxLeft)}</strong><small>한도 ${fmt(PRM_CONFIG.baseline.maxLoss)}</small></div>
  </div>
  <div class="grid2"><div class="panel"><h2>계좌 건강도</h2><div class="healthbar"><i style="width:${health.score}%"></i></div><div class="meterlabels"><span>위험</span><span>${health.score}/100</span><span>안정</span></div><div class="riskstrip" style="margin-top:14px"><div class="riskbox"><b>하이닉스 집중도</b><strong>${pct(health.concentration)}</strong></div><div class="riskbox"><b>레버리지</b><strong>${pct(health.leverage)}</strong></div><div class="riskbox"><b>월 손실 사용</b><strong>${fmt(state.monthlyLoss||0)}</strong></div><div class="riskbox"><b>월 손실 여유</b><strong>${fmt(monthlyLeft)}</strong></div></div></div><div class="panel"><h2>종목별 자산 구성</h2>${composition(r)}</div></div></section>
  <section id="portfolio" class="panel"><h2>포트폴리오</h2><div class="tablewrap"><table><thead><tr><th>종목</th><th>구분</th><th>수량</th><th>평단</th><th>시가</th><th>현재가</th><th>평가액</th><th>손익</th><th>수익률</th><th>비중</th><th>융자</th></tr></thead><tbody>${positionRows(r)}</tbody></table></div><p class="muted">장중 현재가가 평가금액·손익·순자산·담보비율에 자동 반영됩니다. 시세 연결 실패 시 마지막 확정 종가를 사용합니다.</p></section>
  <section id="risk" class="grid2"><div class="panel"><h2>리스크센터</h2>${[180,170,160,150,140].map(x=>{const th=PRMRisk.hynixThreshold(state,x);const zz=PRMRisk.zone(x);return `<div class="threshold"><span><span class="badge ${zz.key}">${x}%</span> 도달 하이닉스 가격</span><b>${fmt(th)}</b></div>`}).join('')}<p class="muted">담보비율은 신한증권 공식 산식이 아닌 민감도 추정치입니다.</p></div><div class="panel"><h2>신용상환 시뮬레이터</h2><div class="field"><label>상환액 (예수금 범위 내)</label><input id="repayScenario" type="number" min="0" max="${Math.min(state.cash,r.loan)}" value="${repayScenario}"></div><div class="riskstrip"><div class="riskbox"><b>상환 전 담보</b><strong>${pct(r.collateral)}</strong></div><div class="riskbox"><b>상환 후 담보</b><strong>${pct(afterRepay.collateral)}</strong></div><div class="riskbox"><b>170%까지 필요</b><strong>${fmt(targetRepay170)}</strong></div><div class="riskbox"><b>180%까지 필요</b><strong>${fmt(targetRepay180)}</strong></div></div><p class="muted">실제 담보평가·대용가·신용종류에 따라 증권사 수치와 차이가 날 수 있습니다.</p></div></section>
  <section id="stress" class="panel"><h2>SK하이닉스 스트레스 테스트</h2><div class="sliderrow"><b>${fmt(PRM_CONFIG.stress.min)}</b><input id="hynixSlider" type="range" min="${PRM_CONFIG.stress.min}" max="${PRM_CONFIG.stress.max}" step="${PRM_CONFIG.stress.step}" value="${scenarioPrice}"><b style="text-align:right">${fmt(PRM_CONFIG.stress.max)}</b></div><div class="scenarioCard"><span class="muted">가정 하이닉스 가격</span><strong>${fmt(scenarioPrice)}</strong><div class="scenarioGrid"><div><b>계좌 평가액</b><span>${fmt(scenario.value)}</span></div><div><b>평가손익</b><span class="${cls(scenario.pnl)}">${fmt(scenario.pnl)}</span></div><div><b>순자산</b><span>${fmt(scenario.net)}</span></div><div><b>담보비율</b><span>${pct(scenario.collateral)}</span></div><div><b>건강도</b><span>${scenarioHealth.score}/100 · ${scenarioHealth.zone.emoji}</span></div></div></div><h3>90만~230만원 스트레스 표</h3><div class="tablewrap"><table><thead><tr><th>하이닉스</th><th>평가금액</th><th>평가손익</th><th>순자산</th><th>담보비율</th><th>위험구간</th></tr></thead><tbody>${stressRows()}</tbody></table></div></section>
  <section id="trade" class="grid2"><div class="panel"><h2>거래 입력</h2><div class="formgrid"><div><label>구분</label><select id="kind"><option value="buy">매수</option><option value="sell">매도</option><option value="repay">신용상환</option><option value="deposit">입금</option><option value="withdraw">출금</option></select></div><div><label>종목</label><select id="name">${Object.keys(PRM_CONFIG.tickers).map(x=>`<option>${x}</option>`).join('')}</select></div><div><label>매수유형</label><select id="type"><option>현금</option><option>유통융자</option><option>자기융자</option><option>신용</option></select></div><div><label>수량</label><input id="qty" type="number" min="0" placeholder="주"></div><div><label>가격</label><input id="price" type="number" min="0" placeholder="원"></div><div><label>금액/융자증가/상환</label><input id="amount" type="number" min="0" placeholder="원"></div></div><button id="applyTrade" class="primary" style="margin-top:10px">계좌에 반영</button><div class="field" style="margin-top:14px"><label>이번 달 확정손실 누계</label><input id="monthlyLoss" type="number" min="0" value="${state.monthlyLoss||0}"></div></div><div class="panel"><h2>최근 거래내역</h2>${tradeRows()}</div></section>
  <section id="diary" class="grid2"><div class="panel"><h2>투자일기 자동 생성</h2><textarea id="diaryText">${esc(PRMDiary.generate(state))}</textarea><div style="margin-top:8px"><button id="downloadDiary">TXT 저장</button><button id="copyDiary">클립보드 복사</button></div></div><div class="panel"><h2>AI 리스크 코치</h2><p>${esc(PRMAI.coach(state))}</p><pre>${esc(PRMAI.prompt(state))}</pre><p class="muted">이 영역은 현재 계좌 데이터를 AI에게 전달할 수 있도록 요약한 프롬프트입니다.</p></div></section>
  <section id="history" class="panel"><h2>타임머신 · 계좌 스냅샷</h2>${snapshotRows()}</section>
  <div class="footerNote">Richman v${PRM_CONFIG.version} · 장중 시세 기반 리스크 관리 도구 · 담보비율은 추정치이므로 실제 주문/반대매매 판단은 증권사 공식 수치를 우선하세요.</div>`;
  bind();
}
function bind(){
  document.querySelectorAll('[data-price-i]').forEach(el=>el.onchange=e=>{state.positions[+e.target.dataset.priceI].price=+e.target.value||0;PRMPortfolio.save(state);scenarioPrice=PRMRisk.hynixCurrent(state);render()});
  document.getElementById('refresh').onclick=refresh;
  document.getElementById('snap').onclick=()=>{PRMStorage.snapshot(JSON.parse(JSON.stringify(state)));render()};
  document.getElementById('backup').onclick=()=>download('richman-v8-backup.json',PRMStorage.exportAll(),'application/json');
  document.getElementById('restoreBtn').onclick=()=>document.getElementById('restoreFile').click();
  document.getElementById('restoreFile').onchange=restoreBackup;
  document.getElementById('reset').onclick=()=>{if(confirm('현재 로컬 계좌 데이터를 기준계좌로 초기화할까요? 백업을 먼저 권장합니다.')){state=PRMPortfolio.reset();scenarioPrice=PRMRisk.hynixCurrent(state);repayScenario=0;render()}};
  document.getElementById('hynixSlider').oninput=e=>{scenarioPrice=+e.target.value;render()};
  document.getElementById('repayScenario').onchange=e=>{repayScenario=+e.target.value||0;render()};
  document.getElementById('monthlyLoss').onchange=e=>{PRMPortfolio.setMonthlyLoss(state,+e.target.value||0);render()};
  document.getElementById('applyTrade').onclick=()=>{const t={kind:document.getElementById('kind').value,name:document.getElementById('name').value,type:document.getElementById('type').value,qty:+document.getElementById('qty').value||0,price:+document.getElementById('price').value||0,amount:+document.getElementById('amount').value||0};PRMPortfolio.trade(state,t);scenarioPrice=PRMRisk.hynixCurrent(state);render()};
  document.getElementById('downloadDiary').onclick=()=>download('investment-diary.txt',document.getElementById('diaryText').value,'text/plain');
  document.getElementById('copyDiary').onclick=async()=>{try{await navigator.clipboard.writeText(document.getElementById('diaryText').value);alert('투자일기를 복사했습니다.')}catch{alert('브라우저에서 클립보드 권한을 허용해 주세요.')}};
  document.querySelectorAll('[data-load-snap]').forEach(btn=>btn.onclick=e=>{const arr=PRMStorage.get('snapshots',[]).slice(-12).reverse(),x=arr[+e.target.dataset.loadSnap];if(x&&confirm('이 스냅샷 상태로 현재 계좌를 바꿀까요?')){state=JSON.parse(JSON.stringify(x.state));PRMPortfolio.save(state);scenarioPrice=PRMRisk.hynixCurrent(state);render()}});
}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:type||'text/plain'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function restoreBackup(e){const f=e.target.files&&e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const d=JSON.parse(rd.result);if(d.state){PRMStorage.set('state',d.state);if(Array.isArray(d.snapshots))PRMStorage.set('snapshots',d.snapshots);if(Array.isArray(d.trades))PRMStorage.set('trades',d.trades);state=PRMPortfolio.initial();scenarioPrice=PRMRisk.hynixCurrent(state);render()}}catch(err){alert('백업 파일을 읽지 못했습니다.')}};rd.readAsText(f)}
async function refresh(){await PRMMarket.refresh();syncPrices();render()}
render();refresh();
setInterval(()=>{if(document.visibilityState==='visible')refresh()},60000);
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refresh()});
